### ISSUE TITLE
Add new domains

### ISSUE THREAD

**Issue by aurieh** [whats-this/owo.py#3]
Add:
`i.am-a.ninja`
`nyanyanya.moe`
`buttsare.sexy`

**Comment by martmists** [comment]
Working on it.

Configurable, or return all?

In case of return all:
`["https://i.am-a.ninja/file.png","https://nyanyanya.moe/file.png", ...]`
or
`{"nyanyanya.moe":"https://nyanyanya.moe/file.png", ...}`

**Comment by jakeoid** [comment]
Configurable

**Comment by sr229** [comment]
at least make it configurable IMHO

useful if guy doesn't want verbose

**Comment by aurieh** [comment]
Configurable 👍

**Comment by martmists** [comment]
Is a `verbose` kwarg/flag acceptable?

**Comment by aurieh** [comment]
That would work. /shrug
